version: "3"

services:
  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    volumes:
      - ./api/src/:/app/src/
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  redis:
    image: redis
    ports:
      - "6379:6379"
  imaginary:
    image: h2non/imaginary
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
      - DEBUG="*"
    #    command: -concurrency 50
    command: -concurrency 50 -enable-url-signature -url-signature-key locallocallocallocallocallocallocallocallocallocal

volumes:
  database-data:
