name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.17.0"

      - name: Install dependencies
        run: yarn

      - name: Install web dependencies
        run: yarn workspace web install

      - name: API
        run: cd api && make check

      # - name: Web
      #   run: cd web && make check

      # - name: Admin
      #   run: cd admin && make check
